# Generated by Django 5.0.6 on 2024-05-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lidoapp', '0001_initial'),
    ]

    operations = [
    ]
